trigger:
  - master

pool:
    vmImage: 'Ubuntu-16.04'

steps:
  - task: CmdLine@2
    inputs:
      script: 'curl -X POST 'http://ec2-18-224-155-110.us-east-2.compute.amazonaws.com:9000/api/projects/create?key=Ktest5&name=Ntest5' -u "admin:admin" -H 'Content-Type: application/json'' 
      failOnStandardError: true
  
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml' 
      goals: 'package'
      publishJUnitResults: true 
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
  	  publishJUnitResults == True
  
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: "JaCoCo"
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
      failIfCoverageEmpty: true

	  
	  
